version: '2'
services:
  ykat-vue:
    image: daocloud.io/shenaishiren/ykat-vue
    container_name: ykat-vue
    ports:
      - "8082:80"
  ykat-node:
    image: daocloud.io/shenaishiren/ykat-node
    container_name: ykat-node
    ports:
      - "8081:8081"
  ykat-spring:
    image: tomcat
    container_name: ykat-spring
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - /root/yikaaitu/spring-end/PTsix:/usr/local/tomcat/webapps
  ykat-mysql:
    image: mysql
    container_name: ykat-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=YKAT
    ports:
      - "3306:3306"
    volumes:
      - /data/db:/data/db
      - /var/lib/mysql:/var/lib/mysql
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
