version: '2'
services:
  ykat-vue:
    image: daocloud.io/shenaishiren/ykat-vue
    container_name: ykat-vue
    ports:
      - "8082:80"
  ykat-node:
    image: daocloud.io/shenaishiren/ykat-node
    container_name: ykat-node
    ports:
      - "8081:8081"
  ykat-spring:
    image: daocloud.io/shenaishiren/ykat-spring
    container_name: ykat-spring
    ports:
      - "8080:8080"
    privileged: true
  ykat-mysql:
    image: daocloud.io/shenaishiren/xiaodi-mysql-auth
    container_name: ykat-mysql
    environment:
      - MYSQL_DATABASE=YKAT
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
    - /data/db:/data/db